[book]
authors = ["Pedro Alonso"]
language = "es"
multilingual = false
src = "src"
title = "Algebra Lineal - Apuntes"
[output.html]
mathjax-support = true
[build]
build-dir = "docs"
create-missing = true
